INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Atlanta United FC", "Guzan, B", 40, 14, 26)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Chicago Fire", "Sánchez, R", 55, 20, 34)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Colorado Rapids", "Howard, T", 43, 15, 28)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Columbus Crew SC", "Steffen, Z", 39, 9, 30)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("DC United", "Ousted, D", 35, 12, 23)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("FC Dallas", "Maurer, J", 38, 11, 28)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Houston Dynamo", "Willis, J", 33, 12, 21)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Houston Dynamo", "Seitz, C", 20, 8, 12)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Los Angeles Football Club", "Miller, T", 55, 19, 36)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("LA Galaxy", "Bingham, D", 69, 22, 48)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Minnesota United FC", "Shuttleworth, B", 46, 10, 36)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Minnesota United FC", "Lampson, M", 34, 12, 22)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Montreal Impact", "Bush, E", 92, 29, 64)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("New England Revolution", "Turner, M", 65, 19, 48)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("New York City FC", "Johnson, S", 66, 19, 48)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("New York Red Bulls", "Robles, L", 34, 11, 23)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Orlando City SC", "Bendik, J", 55, 20, 35)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Philadelphia Union", "Blake, A", 65, 16, 49)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Portland Timbers", "Attinella, J", 18, 3, 16)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Portland Timbers", "Gleeson, J", 29, 14, 15)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Real Salt Lake", "Rimando, N", 76, 26, 50)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("San Jose Earthquakes", "Tarbell, A", 62, 23, 39)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Seattle Sounders FC", "Frei, S", 41, 12, 29)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Sporting Kansas City", "Melia, T", 58, 13, 45)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Toronto FC", "Bono, A", 34, 11, 23)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Toronto FC", "Irwin, C", 24, 9, 15)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Vancouver Whitecaps FC", "Marinovic, S", 42, 18, 25)
INSERT INTO defense (team,player,SA,GA,saves) VALUES ("Vancouver Whitecaps FC", "Rowe, B", 18, 9, 9)