INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Atlanta United FC", 1, "Guzan, B", 41, 15, 26);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Chicago Fire", 17, "Sanchez, R", 58, 21, 36);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Colorado Rapids", 23, "Howard, T", 43, 15, 30);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Columbus Crew SC", 3, "Steffen, Z", 39, 9, 30);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("DC United", 20, "Ousted, D", 35, 12, 23);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("FC Dallas", 8, "Maurer, J", 38, 11, 28);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Houston Dynamo", 10, "Willis, J", 33, 12, 23);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Houston Dynamo", 10, "Seitz, C", 20, 8, 12);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Los Angeles Football Club", 6, "Miller, T", 55, 19, 41);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("LA Galaxy", 13, "Bingham, D", 69, 22, 57);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Minnesota United FC", 14, "Shuttleworth, B", 46, 10, 40);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Minnesota United FC", 14, "Lampson, M", 34, 12, 22);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Montreal Impact", 19, "Bush, E", 92, 29, 64);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("New England Revolution", 11, "Turner, M", 65, 19, 51);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("New York City FC", 4, "Johnson, S", 66, 19, 50);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("New York Red Bulls", 5, "Robles, L", 34, 11, 23);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Orlando City SC", 9, "Bendik, J", 55, 20, 37);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Philadelphia Union", 16, "Blake, A", 65, 16, 55);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Portland Timbers", 7, "Attinella, J", 18, 3, 18);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Portland Timbers", 7, "Gleeson, J", 29, 14, 15);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Real Salt Lake", 15, "Rimando, N", 76, 26, 50);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("San Jose Earthquakes", 21, "Tarbell, A", 62, 23, 41);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Seattle Sounders FC", 22, "Frei, S", 41, 12, 33);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Sporting Kansas City", 2, "Melia, T", 58, 13, 47);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Toronto FC", 18, "Bono, A", 34, 11, 27);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Toronto FC", 18, "Irwin, C", 24, 9, 15);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Vancouver Whitecaps FC", 12, "Marinovic, S", 42, 18, 25);
INSERT INTO Defenses (name,teamID,player,SA,GA,saves) VALUES ("Vancouver Whitecaps FC", 12, "Rowe, B", 18, 9, 9);