INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Atlanta United FC", 1, "Martinez,J", 9, 19, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Atlanta United FC", 1, "Almiron,M", 6, 20, 5);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Atlanta United FC", 1, "Barco,E", 3, 7, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Chicago Fire", 17, "Nikolic,N", 6, 12, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Chicago Fire", 17, "Gordon,A", 3, 9, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Chicago Fire", 17, "Katal,A", 3, 13, 2);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Colorado Rapids", 23, "Badji,D", 5, 12, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Colorado Rapids", 23, "Mason,J", 2, 4, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Colorado Rapids", 23, "Boli,Y", 1, 12, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Columbus Crew SC", 3, "Zardes,G", 8, 17, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Columbus Crew SC", 3, "Higuain,F", 3, 8, 5);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Columbus Crew SC", 3, "Abubakar,L", 1, 3, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("D.C. United", 20, "Mattocks,D", 5, 9, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("D.C. United", 20, "Asad,Y", 3, 6, 3);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("D.C. United", 20, "Stieber,Z", 2, 4, 2);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("FC Dallas", 8, "Urruti,M", 6, 15, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("FC Dallas", 8, "Lamah,R", 5, 7, 4);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("FC Dallas", 8, "Colman,C", 2, 10, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Houston Dynamo", 10, "Ellis,A", 8, 27, 5);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Houston Dynamo", 10, "Manotas,M", 5, 13, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Houston Dynamo", 10, "Martinez,T", 3, 4, 9);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Los Angeles FC", 6, "Vela,C", 7, 16, 5);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Los Angeles FC", 6, "Rossi,D", 5, 15, 6);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Los Angeles FC", 6, "Blessing,L", 2, 7, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Los Angeles Galaxy", 13, "Ibrahimovic,Z", 5, 13, 3);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Los Angeles Galaxy", 13, "Kamara,O", 5, 11, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Los Angeles Galaxy", 13, "Alessandrini,R", 2, 8, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Minnesota United FC", 14, "Quintero,D", 3, 6, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Minnesota United FC", 14, "Ramirez,C", 3, 6, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Minnesota United FC", 14, "Finlay,E", 2, 5, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Montreal Impact", 19, "Platti,I", 5, 8, 6);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Montreal Impact", 19, "Vargas,J", 3, 9, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Montreal Impact", 19, "Edwards,R", 2, 7, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("New England Revolution", 11, "Bunbury,T", 7, 17, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("New England Revolution", 11, "Penilla,C", 5, 15, 4);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("New England Revolution", 11, "Fagundez,D", 3, 10, 3);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("New York City FC", 4, "Villa,D", 8, 15, 3);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("New York City FC", 4, "Moralez,M", 5, 10, 4);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("New York City FC", 4, "Tajouri,I", 5, 5, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("New York Red Bulls", 5, "Wright-Phillips,B", 8, 12, 5);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("New York Red Bulls", 5, "Etienne,D", 3, 7, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("New York Red Bulls", 5, "Romero Gamarra,A", 3, 11, 9);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Orlando City SC", 9, "Dwyer,D", 6, 11, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Orlando City SC", 9, "Higuta,C", 3, 4, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Orlando City SC", 9, "Mueller,C", 3, 6, 2);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Philadelphia Union", 16, "Dockal,B", 3, 10, 6);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Philadelphia Union", 16, "Itsinho,M", 3, 4, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Philadelphia Union", 16, "Burke,C", 2, 4, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Portland Timbers", 7, "Blanco,S", 5, 11, 4);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Portland Timbers", 7, "Valeri,D", 5, 11, 3);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Portland Timbers", 7, "Armenteros,S", 3, 4, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Real Salt Lake", 15, "Baird,C", 3, 9, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Real Salt Lake", 15, "Plata,J", 3, 13, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Real Salt Lake", 15, "Rusnak,A", 3, 10, 3);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("San Jose Earthquakes", 21, "Hoesen,D", 6, 20, 2);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("San Jose Earthquakes", 21, "Eriksson,M", 3, 9, 3);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("San Jose Earthquakes", 21, "Jungwirth,F", 2, 4, 2);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Seattle Sounders FC", 22, "Bruin,W", 3, 9, 2);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Seattle Sounders FC", 22, "Bwana,H",1, 1, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Seattle Sounders FC", 22, "Delem,J",1, 1, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Sporting Kansas City", 2, "Gutierrez,F",5, 10, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Sporting Kansas City", 2, "Russell,J",5, 18, 3);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Sporting Kansas City", 2, "Salloi,D",3, 13, 4);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Toronto FC", 18, "Altidore,J",2, 4, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Toronto FC", 18, "Chapman,J",2, 5, 0);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Toronto FC", 18, "Giovinco,S",2, 19, 4);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Vancouver Whitecaps FC", 12, "Techera,C",5, 10, 1);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Vancouver Whitecaps FC", 12, "Kamara,K",4, 9, 3);
INSERT INTO Offenses (name,teamID,player,goals,sog,assists) VALUES ("Vancouver Whitecaps FC", 12, "Shea,B",3, 6, 0);


