INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Atlanta United FC", "Martinez,J", 9, 19, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Atlanta United FC", "Almiron,M", 6, 20, 5);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Atlanta United FC", "Barco,E", 3, 7, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Chicago Fire", "Nikolic,N", 6, 12, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Chicago Fire", "Gordon,A", 3, 9, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Chicago Fire", "Katal,A", 3, 13, 2);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Colorado Rapids", "Badji,D", 5, 12, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Colorado Rapids", "Mason,J", 2, 4, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Colorado Rapids", "Boli,Y", 1, 12, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Columbus Crew SC", "Zardes,G", 8, 17, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Columbus Crew SC", "Higuain,F", 3, 8, 5);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Columbus Crew SC", "Abubakar,L", 1, 3, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("D.C. United", "Mattocks,D", 5, 9, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("D.C. United", "Asad,Y", 3, 6, 3);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("D.C. United", "Stieber,Z", 2, 4, 2);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("FC Dallas", "Urruti,M", 6, 15, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("FC Dallas", "Lamah,R", 5, 7, 4);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("FC Dallas", "Colman,C", 2, 10, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Houston Dynamo", "Ellis,A", 8, 27, 5);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Houston Dynamo", "Manotas,M", 5, 13, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Houston Dynamo", "Martinez,T", 3, 4, 9);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Los Angeles FC", "Vela,C", 7, 16, 5);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Los Angeles FC", "Rossi,D", 5, 15, 6);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Los Angeles FC", "Blessing,L", 2, 7, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Los Angeles Galaxy", "Ibrahimovic,Z", 5, 13, 3);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Los Angeles Galaxy", "Kamara,O", 5, 11, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Los Angeles Galaxy", "Alessandrini,R", 2, 8, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Minnesota United FC", "Quintero,D", 3, 6, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Minnesota United FC", "Ramirez,C", 3, 6, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Minnesota United FC", "Finlay,E", 2, 5, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Montreal Impact", "Platti,I", 5, 8, 6);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Montreal Impact", "Vargas,J", 3, 9, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Montreal Impact", "Edwards,R", 2, 7, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("New England Revolution", "Bunbury,T", 7, 17, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("New England Revolution", "Penilla,C", 5, 15, 4);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("New England Revolution", "Fagundez,D", 3, 10, 3);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("New York City FC", "Villa,D", 8, 15, 3);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("New York City FC", "Moralez,M", 5, 10, 4);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("New York City FC", "Tajouri,I", 5, 5, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("New York Red Bulls", "Wright-Phillips,B", 8, 12, 5);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("New York Red Bulls", "Etienne,D", 3, 7, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("New York Red Bulls", "Romero Gamarra,A", 3, 11, 9);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Orlando City SC", "Dwyer,D", 6, 11, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Orlando City SC", "Higuta,C", 3, 4, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Orlando City SC", "Mueller,C", 3, 6, 2);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Philadelphia Union", "Dockal,B", 3, 10, 6);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Philadelphia Union", "Itsinho,M", 3, 4, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Philadelphia Union", "Burke,C", 2, 4, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Portland Timbers", "Blanco,S", 5, 11, 4);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Portland Timbers", "Valeri,D", 5, 11, 3);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Portland Timbers", "Armenteros,S", 3, 4, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Real Salt Lake", "Baird,C", 3, 9, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Real Salt Lake", "Plata,J", 3, 13, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Real Salt Lake", "Rusnak,A", 3, 10, 3);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("San Jose Earthquakes", "Hoesen,D", 6, 20, 2);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("San Jose Earthquakes", "Eriksson,M", 3, 9, 3);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("San Jose Earthquakes", "Jungwirth,F", 2, 4, 2);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Seattle Sounders FC", "Bruin,W", 3, 9, 2);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Seattle Sounders FC", "Bwana,H",1, 1, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Seattle Sounders FC", "Delem,J",1, 1, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Sporting Kansas City", "Gutierrez,F",5, 10, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Sporting Kansas City", "Russell,J",5, 18, 3);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Sporting Kansas City", "Salloi,D",3, 13, 4);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Toronto FC", "Altidore,J",2, 4, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Toronto FC", "Chapman,J",2, 5, 0);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Toronto FC", "Giovinco,S",2, 19, 4);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Vancouver Whitecaps FC", "Techera,C",5, 10, 1);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Vancouver Whitecaps FC", "Kamara,K",4, 9, 3);
INSERT INTO offense (name,player,goals,sog,assists) VALUES ("Vancouver Whitecaps FC", "Shea,B",3, 6, 0);


