INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Atlanta United FC", 9, 3, 2, 29, 30);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Sporting Kansas City", 8, 2, 4, 28, 28);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Columbus Crew SC", 7, 3, 5, 26, 21);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("New York City FC", 8, 3, 3, 27, 29);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("New York Red Bulls", 7, 4, 1, 22, 27);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Los Angeles Football Club", 6, 4, 3, 21, 25);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Portland Timbers", 6, 3, 3, 21, 20);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("FC Dallas", 7, 1, 5, 26, 22);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Orlando City SC", 6, 6, 1, 19, 22);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Houston Dynamo", 5, 5, 3, 18, 27);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("New England Revolution", 6, 4, 4, 22, 24);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Vancouver Whitecaps FC", 5, 5, 5, 20, 21);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("LA Galaxy", 5, 7, 2, 17, 19);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Minnesota United FC", 5, 8, 1, 16, 17);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Real Salt Lake", 7, 6, 1, 22, 19);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Philadelphia Union", 5, 6, 3, 18, 16);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Chicago Fire", 5, 7, 2, 17, 20);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Toronto FC", 3, 7, 2, 11, 17);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Montreal Impact", 4, 10, 0, 12, 15);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("DC United", 2, 5, 3, 9, 14);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("San Jose Earthquakes", 2, 8, 3, 9, 19);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Seattle Sounders FC", 2, 7, 2, 8, 7);
INSERT INTO Teams (name,wins,losses,draws,points,goals) VALUES ("Colorado Rapids", 2, 8, 2, 8, 14);