NSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Atlanta United FC", 8, 3, 1, 25, 2.08);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Sporting Kansas City", 7, 2, 4, 25, 1.92);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Columbus Crew SC", 7, 3, 4, 25, 1.79);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("New York City FC", 7, 3, 3, 24, 1.85);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("New York Red Bulls", 7, 3, 1, 22, 2.0);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Los Angeles Football Club", 6, 3, 3, 21, 1.75);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Portland Timbers", 6, 3, 2, 20, 1.82);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("FC Dallas", 5, 1, 5, 20, 1.82);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Orlando City SC", 6, 5, 1, 19, 1.58);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Houston Dynamo", 5, 3, 3, 18, 1.65);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("New England Revolution", 5, 4, 3, 18, 1.50);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Vancouver Whitecaps FC", 4, 5, 5, 17, 1.21);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("LA Galaxy", 5, 6, 1, 16, 1.33);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Minnesota United FC", 5, 7, 1, 16, 1.23);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Real Salt Lake", 5, 6, 1, 16, 1.33);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Philadelphia Union", 4, 5, 3, 15, 1.25);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Chicago Fire", 4, 6, 2, 14, 1.17);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Toronto FC", 3, 7, 1, 10, 0.91);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Montreal Impact", 3, 10, 0, 9, 0.75);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("DC United", 2, 5, 3, 9, 0.9);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("San Jose Earthquakes", 2, 6, 3, 9, 0.75);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Seattle Sounders FC", 2, 6, 2, 9, 0.8);
INSERT INTO teams (name,wins,losses,draws,points,ppg) VALUES ("Colorado Rapids", 2, 7, 2, 8, 0.73);