INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Atlanta United FC", 8, 3, 2, 26, 27);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Sporting Kansas City", 7, 2, 4, 25, 24);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Columbus Crew SC", 7, 3, 4, 25, 18);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("New York City FC", 7, 3, 3, 24, 26);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("New York Red Bulls", 7, 3, 1, 22, 26);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Los Angeles Football Club", 6, 3, 3, 21, 24);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Portland Timbers", 6, 3, 2, 20, 19);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("FC Dallas", 6, 1, 5, 23, 20);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Orlando City SC", 6, 5, 1, 19, 22);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Houston Dynamo", 5, 4, 3, 18, 27);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("New England Revolution", 5, 4, 4, 19, 22);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Vancouver Whitecaps FC", 5, 5, 5, 20, 21);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("LA Galaxy", 5, 7, 1, 16, 18);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Minnesota United FC", 5, 7, 1, 16, 16);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Real Salt Lake", 6, 6, 1, 19, 17);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Philadelphia Union", 5, 5, 3, 18, 15);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Chicago Fire", 4, 7, 2, 14, 18);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Toronto FC", 3, 7, 1, 10, 14);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Montreal Impact", 3, 10, 0, 9, 14);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("DC United", 2, 5, 3, 9, 14);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("San Jose Earthquakes", 2, 6, 3, 9, 18);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Seattle Sounders FC", 2, 6, 2, 9, 7);
INSERT INTO teams (name,wins,losses,draws,points,goals) VALUES ("Colorado Rapids", 2, 8, 2, 8, 14);